# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [15]:
!pip install numpy==1.23.5

Defaulting to user installation because normal site-packages is not writeable
Collecting numpy==1.23.5
  Downloading numpy-1.23.5.tar.gz (10.7 MB)
     ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
      --------------------------------------- 0.1/10.7 MB 1.7 MB/s eta 0:00:07
     - -------------------------------------- 0.3/10.7 MB 2.1 MB/s eta 0:00:05
     - -------------------------------------- 0.4/10.7 MB 2.1 MB/s eta 0:00:05
     - -------------------------------------- 0.5/10.7 MB 2.4 MB/s eta 0:00:05
     -- ------------------------------------- 0.7/10.7 MB 2.5 MB/s eta 0:00:04
     --- ------------------------------------ 0.8/10.7 MB 2.7 MB/s eta 0:00:04
     --- ------------------------------------ 1.0/10.7 MB 2.8 MB/s eta 0:00:04
     ---- ----------------------------------- 1.2/10.7 MB 2.9 MB/s eta 0:00:04
     ----- ---------------------------------- 1.4/10.7 MB 3.0 MB/s eta 0:00:04
     ----- ---------------------------------- 1.5/10.7 MB 3.1 MB/s eta 0:00:03
     ------ --------------------------------- 1.6/10.7 MB 3.1 MB/s eta 0:00:03
     ------- -------------------------------- 1.9/10.7 MB 3.2 MB/s eta 0:00:03
     ------- -------------------------------- 2.1/10.7 MB 3.3 MB/s eta 0:00:03
     -------- ------------------------------- 2.2/10.7 MB 3.2 MB/s eta 0:00:03
     --------- ------------------------------ 2.5/10.7 MB 3.4 MB/s eta 0:00:03
     ---------- ----------------------------- 2.7/10.7 MB 3.5 MB/s eta 0:00:03
     ----------- ---------------------------- 3.0/10.7 MB 3.6 MB/s eta 0:00:03
     ----------- ---------------------------- 3.2/10.7 MB 3.7 MB/s eta 0:00:03
     ------------ --------------------------- 3.4/10.7 MB 3.7 MB/s eta 0:00:02
     ------------- -------------------------- 3.7/10.7 MB 3.9 MB/s eta 0:00:02
     -------------- ------------------------- 3.9/10.7 MB 3.8 MB/s eta 0:00:02
     --------------- ------------------------ 4.2/10.7 MB 4.0 MB/s eta 0:00:02
     ----------------- ---------------------- 4.6/10.7 MB 4.1 MB/s eta 0:00:02
     ------------------ --------------------- 4.9/10.7 MB 4.2 MB/s eta 0:00:02
     ------------------ --------------------- 5.0/10.7 MB 4.3 MB/s eta 0:00:02
     -------------------- ------------------- 5.4/10.7 MB 4.4 MB/s eta 0:00:02
     --------------------- ------------------ 5.7/10.7 MB 4.4 MB/s eta 0:00:02
     ---------------------- ----------------- 6.0/10.7 MB 4.5 MB/s eta 0:00:02
     ----------------------- ---------------- 6.2/10.7 MB 4.6 MB/s eta 0:00:01
     ------------------------ --------------- 6.7/10.7 MB 4.7 MB/s eta 0:00:01
     -------------------------- ------------- 7.0/10.7 MB 4.8 MB/s eta 0:00:01
     -------------------------- ------------- 7.2/10.7 MB 4.8 MB/s eta 0:00:01
     ---------------------------- ----------- 7.6/10.7 MB 4.8 MB/s eta 0:00:01
     ----------------------------- ---------- 7.8/10.7 MB 4.9 MB/s eta 0:00:01
     ------------------------------ --------- 8.1/10.7 MB 4.9 MB/s eta 0:00:01
     ------------------------------- -------- 8.4/10.7 MB 5.0 MB/s eta 0:00:01
     ------------------------------- -------- 8.6/10.7 MB 4.9 MB/s eta 0:00:01
     --------------------------------- ------ 8.9/10.7 MB 4.9 MB/s eta 0:00:01
     ---------------------------------- ----- 9.1/10.7 MB 4.9 MB/s eta 0:00:01
     ---------------------------------- ----- 9.3/10.7 MB 5.0 MB/s eta 0:00:01
     ------------------------------------ --- 9.7/10.7 MB 5.0 MB/s eta 0:00:01
     ------------------------------------- -- 10.0/10.7 MB 5.0 MB/s eta 0:00:01
     -------------------------------------- - 10.3/10.7 MB 5.2 MB/s eta 0:00:01
     ---------------------------------------  10.6/10.7 MB 5.4 MB/s eta 0:00:01
     ---------------------------------------- 10.7/10.7 MB 5.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [33 lines of output]
  Traceback (most recent call last):
    File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "C:\Users\Kelly\AppData\Local\Temp\pip-build-env-mzi44e35\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
      import setuptools.version
    File "C:\Users\Kelly\AppData\Local\Temp\pip-build-env-mzi44e35\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
      import pkg_resources
    File "C:\Users\Kelly\AppData\Local\Temp\pip-build-env-mzi44e35\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [16]:
from faker import Faker
import pandas as pd
import numpy as np
import random
fake = Faker()

In [17]:
files= 'data/data_500.csv'
df_csv = pd.read_csv(files)
df_csv.info()
df_csv.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   idHistory         500 non-null    object
 1   vehicle_type      500 non-null    object
 2   vehicle_name      500 non-null    object
 3   fuel_type         500 non-null    object
 4   machine_capacity  500 non-null    int64
 5   daily_emission    500 non-null    int64
 6   distance          500 non-null    int64
 7   location          500 non-null    object
 8   location_address  500 non-null    object
 9   time_used         500 non-null    object
 10  time_travel       500 non-null    int64
 11  user_id           0 non-null      float64
dtypes: float64(1), int64(4), object(7)
memory usage: 47.0+ KB

       machine_capacity  daily_emission      distance  time_travel  user_id
count        500.000000    5.000000e+02    500.000000   500.000000      0.0
mean         839.950000    2.552776e+06  24738.132000   102.918000      NaN
std          710.711241    1.413948e+06  14316.117136    58.827993      NaN
min          100.000000    1.020300e+04    304.000000     1.000000      NaN
25%          150.000000    1.332468e+06  12334.000000    52.000000      NaN
50%         1000.000000    2.588752e+06  24377.000000   104.000000      NaN
75%         1500.000000    3.826501e+06  37199.250000   154.250000      NaN
max         2000.000000    4.996207e+06  49719.000000   200.000000      NaN

In [7]:
df_csv.head()

,idHistory,vehicle_type,vehicle_name,fuel_type,machine_capacity,daily_emission,distance,location,location_address,time_used,time_travel,user_id
0,2be4f812-81b0-4df2-a831-614e56a15e95,mobil,Suzuki Ertiga,Pertalite,250,805512,1479,Warkop Pak Min,"Turus, Ternyang, Sumberpucung, Malang Regency,...",2023-03-21 00:00:00,120,NaN
1,0acfb7fb-ada5-4a7a-9f78-72645935c820,sepeda motor,Honda Beat,Pertamax Turbo,2000,806546,36364,sabila snack,"Jalan Randupitu-Gunung Gangsir, Pagar Gunung, ...",2023-08-29 00:00:00,159,NaN
2,f7feef39-033e-4a8b-a186-934365248ccc,mobil,Suzuki Ertiga,Diesel,150,4259071,12174,Universitas Yudharta Pasuruan,"Jl. Yudharta, Kembangkuning, Sengonagun, Pasur...",2023-06-05 00:00:00,153,NaN
3,d10cec6b-e90d-42ca-aef6-dfd325022df8,sepeda motor,Kawasaki Ninja,Shell Super,1800,3059045,6517,Pakuwon Mall,"Jalan Mayjend. Jonosewojo, Babatan, Surabaya, ...",2023-06-29 00:00:00,176,NaN
4,d82fbea0-e18e-4738-8725-c2e765496486,mobil,Toyota Avanza,Shell Super,200,3480107,20097,Jalan Semampir Tengah IIA No.17,"Medokan Semampir, Surabaya, East Java, Indonesia",2023-02-20 00:00:00,110,NaN

In [18]:
def generate_data_user(df_csv, num_user):
    user_ids = [fake.unique.uuid4() for _ in range(num_user)]
    
    user_id = (user_ids * (len(df_csv) // num_user))[:len(df_csv)]
    random.shuffle(user_id)
    df_csv['user_id'] = user_id
    
    return df_csv

test = generate_data_user(df_csv, 50)
df_csv.head()

,idHistory,vehicle_type,vehicle_name,fuel_type,machine_capacity,daily_emission,distance,location,location_address,time_used,time_travel,user_id
0,2be4f812-81b0-4df2-a831-614e56a15e95,mobil,Suzuki Ertiga,Pertalite,250,805512,1479,Warkop Pak Min,"Turus, Ternyang, Sumberpucung, Malang Regency,...",2023-03-21 00:00:00,120,1bddac80-08b8-4054-9715-d7b33e6aede2
1,0acfb7fb-ada5-4a7a-9f78-72645935c820,sepeda motor,Honda Beat,Pertamax Turbo,2000,806546,36364,sabila snack,"Jalan Randupitu-Gunung Gangsir, Pagar Gunung, ...",2023-08-29 00:00:00,159,8e0add54-dd73-4ba2-aca5-1d9b3b2a8360
2,f7feef39-033e-4a8b-a186-934365248ccc,mobil,Suzuki Ertiga,Diesel,150,4259071,12174,Universitas Yudharta Pasuruan,"Jl. Yudharta, Kembangkuning, Sengonagun, Pasur...",2023-06-05 00:00:00,153,2d627fcf-00ca-4715-88df-c303c0e79c6e
3,d10cec6b-e90d-42ca-aef6-dfd325022df8,sepeda motor,Kawasaki Ninja,Shell Super,1800,3059045,6517,Pakuwon Mall,"Jalan Mayjend. Jonosewojo, Babatan, Surabaya, ...",2023-06-29 00:00:00,176,f0b2ba4f-aa0d-431d-92c3-bb4482c12765
4,d82fbea0-e18e-4738-8725-c2e765496486,mobil,Toyota Avanza,Shell Super,200,3480107,20097,Jalan Semampir Tengah IIA No.17,"Medokan Semampir, Surabaya, East Java, Indonesia",2023-02-20 00:00:00,110,f1b6237e-3251-4e2d-8e91-44482b6a88ca

To check if the user_id is well-distributed.

In [19]:
df_csv['user_id'].value_counts()

user_id
1bddac80-08b8-4054-9715-d7b33e6aede2    10
8e0add54-dd73-4ba2-aca5-1d9b3b2a8360    10
2d627fcf-00ca-4715-88df-c303c0e79c6e    10
f0b2ba4f-aa0d-431d-92c3-bb4482c12765    10
f1b6237e-3251-4e2d-8e91-44482b6a88ca    10
52c0b3e1-6dd9-46eb-a38e-7121abda2e8e    10
dc5d798b-1b28-4ce7-86a2-208054f9d5e0    10
aa5d5ec3-3795-43ee-9863-ccb39ca2c541    10
48e3c628-f304-4cd4-863a-07d44154b700    10
69efb2dc-920a-4587-a8cb-b512292002fc    10
eb97611b-4fe8-4306-9a13-c27186e88c4e    10
25dde27f-ba58-448b-badb-3387fb73faec    10
d96a0080-cd74-4220-8750-41767ccaf5b2    10
3c1abc94-5c1b-4455-ad84-7623cb0be717    10
cf8fab25-428d-4bda-a7cc-d2c41df0031a    10
5499be1f-b7d4-4550-845c-9a35d9fb7ea1    10
f88ba4d0-ecc2-41b1-8e8c-368e228a71d7    10
9c2000ae-cdaf-44a4-b30e-8d63e519a04d    10
ec932cac-49ad-4fbc-a37d-2d51890f6407    10
98e34e32-2f5b-470b-848a-dfc890432018    10
831877da-f637-480c-b23c-f123de384709    10
d255e079-bb11-4c4a-b1b0-14d5b1e8faf1    10
5f9de1f5-7610-4f90-a19e-5ef0ce3bd08b    10
9ca82dfc-0f52-40cd-9c48-49209bb45d49    10
ea386190-de87-4848-b4d1-846d0bcaf242    10
5cbadac6-b251-47ba-9704-aa78fb9f6e89    10
9733699d-421f-4c97-9fee-d33417058080    10
06717433-6a58-4c53-aadf-1da945c0ab8c    10
5f656c06-e771-418e-a6bd-3b2048d420be    10
8f0ef735-ae28-4336-8cd5-cea000e2e091    10
ac6b10e8-4c75-4025-a094-f6b5c43a83a3    10
92aea564-919d-4489-a885-66ac52503dcb    10
09ab26ec-4727-4e52-8b4b-c52dc7b5d9c0    10
57a7540c-31b0-48f7-bdf3-a57c0dd648fa    10
a23156e7-a804-4cf4-85e4-ba3bdcfee175    10
6f0d3bd9-6845-4a5b-b9f1-835992951be4    10
e950bc77-b555-446f-93c4-067fd601648d    10
e8001c87-6660-487c-8fde-052aa272df9e    10
f9e7e661-f88a-441b-8629-ffaf324b31bf    10
29f54581-d640-4614-a732-5e26fc5cf358    10
ee580db9-c671-46f6-b66e-f5bfce503902    10
950b529b-1ef9-4fae-ba06-e425cc1ac63d    10
adb67a59-d8d4-476c-bcd1-334416e37c0b    10
76b66b82-bb35-4bc5-ad3a-d3f5435e69a2    10
b53ef9b2-669a-49d2-87c6-8448c937f572    10
49d6672b-e707-4759-8bf7-3f3915b30921    10
bd2655dc-1658-4280-a85e-816f8fa95359    10
465f1632-6bf7-43d5-9b73-a73cdfde58e9    10
dff8deb9-28c3-46db-afa8-a587fa6d9796    10
c3c91c07-1b10-4928-b98f-7b416bbfb4f8    10
Name: count, dtype: int64

Check if user_id is all filled.

In [20]:
df_csv['user_id'].isna().sum()

np.int64(0)

## Creating Challenge Data

In [ ]:
challenges = {
    "chal_name": ""
}